# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the main branch
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [12.x]

    steps:
    - name: Install 
    - run: dir
    - run: cd .. && dir
    - run: cd ../reminder/frontend
    - run: curl -o- -L https://yarnpkg.com/install.sh | bash
    - run: yarn install
    - run: yarn run build 
    - run: cd src-tauri/target/release/
      env:
        CI: true
